name: Continuous Pipeline for CSC8428

on:
  push:
  pull_request:

jobs:
    test:
        name: Testing stuff
        runs-on: ubuntu-latest
        steps:
            # Get the code
            - uses: actions/checkout@v2

            # Install software
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                # Py 3.7 is current default Py3 version on an RPi
                python-version: 3.7

            # dependencies
            - name: Install NodeJS dependencies
              run: npm ci
            - name: Install Python dependencies
              run: pip3 install coverage flake8 opencv-python-headless

            # Test
            - name: Lint and test
              run: npm run test:ci
            